DECLARE @cols NVARCHAR(MAX) = '';

SELECT @cols = STRING_AGG(QUOTENAME(COLUMN_NAME), ', ')
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'PROD_COMP_CMC_TRADES'
  AND COLUMN_NAME IN ('Price', 'Quantity/nominal');

DECLARE @sql NVARCHAR(MAX) = 'SELECT ' + @cols + ' FROM [PROD COMP CMC_TRADES];';
EXEC sp_executesql @sql;

